[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
boss = "HktspUZiuXAUGNsfKD39zLsQGweRUMKKb6JJx4Pf8nWe"

[programs.devnet]
boss = "HktspUZiuXAUGNsfKD39zLsQGweRUMKKb6JJx4Pf8nWe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ha.nguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
